#!/usr/bin/env bash

cd `dirname $0`
. stdlib.sh
cd ..

DESTDIR=$1

if [ -z "$DESTDIR" ]; then
  fail "Missing the first argument: the destination path"
fi

## Build dependencies ##
# FIXME: This should be handled by a dependency system
if ! has ruby1.9.3 ; then
  sudo apt-get install -qy ruby1.9.3 build-essential
  echo gem: --no-ri --no-rdoc | sudo tee /etc/gemrc
  sudo gem install bundler
  sudo gem install berkshelf
fi

if ! has git ; then
  sudo apt-get install -qy git
fi

## Copying the release files ##
rm -rf $DESTDIR
mkdir -p $DESTDIR
cp -r * $DESTDIR
cd $DESTDIR

## Installing the runtime dependencies ##
bundle install --deployment --binstubs=bin --without=development,test
berks install --path vendor/cookbooks
