#!/usr/bin/env bash

set -e

. `dirname $0`/ploy-lib.sh

DEST_DIR=`expand_path "$1"`
CACHE_DIR=`expand_path "$2"`

if [ -z "$DEST_DIR" ]; then
  fail "Missing the first argument: the destination path"
fi

cd `dirname $0`/..

# Build
rm -rf $DEST_DIR
git clone $PWD $DEST_DIR
cd $DEST_DIR

# workaround http->https redirect issue
/opt/chef/embedded/bin/gem install berkshelf --version 2.0.18

## Installing the runtime dependencies ##
BERKSHELF_PATH=$CACHE_DIR/berkshelf berks install --path vendor/cookbooks
