#!/bin/bash
#
# This script prepares the system to run chef.
#

set -e

has() {
  which $1 >/dev/null 2>&1
  return $?
}

if ! has chef-solo ; then
  apt-get update
  wget -nv -c https://www.opscode.com/chef/install.sh
  chmod +x install.sh
  ./install.sh -v 11.4.4
fi
